version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    - echo "zipping deployment package..."
    - cd lib
    - zip -r9 ..deployment_package.zip .
    - cd ..
    - zip -g deployment_package.zip lambda_function.py
  post_build:
    - echo "Uploading to s3 ..."
    - aws s3 cp deployment_package.zip s3://s3-code-build/
    - echo "updating lambda function via s3..."
    - aws lambda update-function-code --function-name github-to-lambda-CICD --s3-bucket s3-code-build --s3-key deployment_package.zip
    - echo "Deployment Completed !!"
